Refactor and fix Debian init scripts.
git-svn-id: https://www.boxbackup.org/svn/box/trunk@2192 9c52e268-1103-0410-960d-c6a436f6b474

diff --git a/contrib/debian/bbstored.in b/contrib/debian/bbstored.in
--- a/contrib/debian/bbstored.in
+++ b/contrib/debian/bbstored.in
@@ -1,46 +1,59 @@
 #! /bin/sh
 
 # Start and stop the Box Backup server daemon.
+# Originally by James Stark, modified by Chris Wilson and James O'Gorman
+# For support, visit http://www.boxbackup.org/trac/wiki/MailingLists
 
-BBSTORED=@sbindir_expanded@/bbstored
-CONFIG=@sysconfdir_expanded@/box/bbstored.conf
-PIDFILE=@localstatedir_expanded@/run/bbstored.pid
+NAME=bbstored
+LONGNAME="Box Backup Server daemon"
+BINARY=@sbindir_expanded@/$NAME
+CONFIG=@sysconfdir_expanded@/box/$NAME.conf
+PIDFILE=@localstatedir_expanded@/run/$NAME.pid
 
-test -x $BBACKUPD || exit 0
+test -x $BINARY || exit 0
 test -f $CONFIG || exit 0
+
+start_stop() {
+	start-stop-daemon --quiet --exec $BINARY --pidfile $PIDFILE "$@"
+}
+
+start_stop_verbose() {
+	if start_stop "$@"; then
+		echo "."
+	else
+		echo " failed!"
+		exit 1
+	fi
+}
 
 case $1 in
 	start)
-		echo -n "Starting Box Backup Server daemon: bbstored"
-		start-stop-daemon --start --quiet --exec $BBSTORED > /dev/null
-		echo "."
+		echo -n "Starting $LONGNAME: $NAME"
+		start_stop_verbose --start
 		;;
 	
 	stop)
-		echo -n "Stopping Box Backup Server daemon: bbstored"
-		start-stop-daemon --stop --quiet \
-			--pidfile $PIDFILE --exec $BBSTORED
-		echo "."
+		echo -n "Stopping $LONGNAME: $NAME"
+		start_stop_verbose --stop
 		;;
 	
 	reload|force-reload)
-		echo -n "Reloading Box Backup Server configuration"
-		start-stop-daemon --stop --signal 1 --quiet --oknodo \
-			--pidfile $PIDFILE --exec $BBSTORED
-		echo "."
+		echo -n "Reloading $LONGNAME configuration"
+		start_stop_verbose --stop --signal 1
 		;;
 	
 	restart)
-		echo -n "Restarting Box Backup Server daemon: bbstored"
-		start-stop-daemon --stop --quiet --pidfile $PIDFILE \
-			--exec $BBSTORED --retry 5
-		start-stop-daemon --start --quiet \
-			--exec $BBSTORED > /dev/null
-		echo "."
+		echo -n "Restarting $LONGNAME: $NAME"
+		if start_stop --stop --retry 5 && start_stop --start; then
+			echo "."
+		else
+			echo " failed!"
+			exit 1
+		fi
 		;;
 	
 	*)
-		echo "Usage: /etc/init.d/bbstored {start|stop|reload|force-reload|restart}"
+		echo "Usage: $0 {start|stop|reload|force-reload|restart}"
 esac
 
 exit 0
