Update contributed scripts to use autoconf substitution for the paths to binaries, configuration files and local state files.

diff --git a/suse/bbackupd.in b/suse/bbackupd.in
--- a/suse/bbackupd.in
+++ b/suse/bbackupd.in
@@ -1,13 +1,13 @@
 #!/bin/sh
 #
 # Copyright (c)2004, Nothing But Net Limited
-#   <chris.smith@nothingbutnet.co.nz>
+#	<chris.smith@nothingbutnet.co.nz>
 #
 ######################################################################
 # RELEASED AND PROVIDED TO YOU UNDER THE SAME LICENCE AS THE BOXBACKUP
 # SUITE OF PROGRAMS. LICENCE MAY BE VIEWED HERE:
 #
-# http://www.fluffy.co.uk/boxbackup/license.html
+# http://www.boxbackup.org/license.html
 ######################################################################
 #
 # /etc/init.d/bbackupd
@@ -22,14 +22,13 @@
 # X-UnitedLinux-Should-Stop: $time ypbind sendmail
 # Default-Start:     3 5
 # Default-Stop:      0 1 2 6
-# Short-Description: BoxBackup server side daemon
+# Short-Description: BoxBackup client side daemon
 # Description: Client daemon for the BoxBackup software       
 #	that allows you to communicate with a bbstored server.
 ### END INIT INFO
-# 
 
 # Check for missing binaries (stale symlinks should not happen)
-BBACKUPD_BIN=/usr/sbin/bbstored
+BBACKUPD_BIN=@bindir_expanded@/bbackupd
 if [ ! -x $BBACKUPD_BIN ] ; then
 	echo "$BBACKUPD_BIN not installed"
 	exit 5
@@ -42,62 +41,63 @@ rc_reset
 
 case "$1" in
 	start)
-	echo -n "Starting bbstored "
-	startproc $BBACKUPD_BIN
-	rc_status -v
-	;;
+		echo -n "Starting bbackupd "
+		startproc $BBACKUPD_BIN
+		rc_status -v
+		;;
 
     stop)
-	echo -n "Shutting down bstored "
-	killproc -TERM $BBACKUPD_BIN
-	rc_status -v
-	;;
+		echo -n "Shutting down bbackupd "
+		killproc -TERM $BBACKUPD_BIN
+		rc_status -v
+		;;
 
     try-restart|condrestart)
-	if test "$1" = "condrestart"; then
-		echo "${attn} Use try-restart ${done}(LSB)${attn} rather than condrestart ${warn}(RH)${norm}"
-	fi
-	$0 status
-	if test $? = 0; then
-		$0 restart
-	else
-		rc_reset	# Not running is not a failure.
-	fi
-	rc_status
-	;;
+		if test "$1" = "condrestart"; then
+			echo "${attn} Use try-restart ${done}(LSB)${attn} rather than condrestart ${warn}(RH)${norm}"
+		fi
+		$0 status
+		if test $? = 0; then
+			$0 restart
+		else
+			rc_reset	# Not running is not a failure.
+		fi
+		rc_status
+		;;
 
     restart)
-	$0 stop
-	$0 start
-	rc_status
-	;;
+		$0 stop
+		$0 start
+		rc_status
+		;;
 
     force-reload)
-	echo -n "Reload service bbstored "
-	killproc -HUP $BBACKUPD_BIN
-	rc_status -v
-	;;
+		echo -n "Reload service bbackupd "
+		killproc -HUP $BBACKUPD_BIN
+		rc_status -v
+		;;
 
     reload)
-	echo -n "Reload service bbstored  "
-	killproc -HUP $BBACKUPD_BIN
-	rc_status -v
-	;;
+		echo -n "Reload service bbackupd  "
+		killproc -HUP $BBACKUPD_BIN
+		rc_status -v
+		;;
 
     status)
-	echo -n "Checking for service bbstored "
-	checkproc $BBACKUPD_BIN
-	rc_status -v
-	;;
+		echo -n "Checking for service bbackupd "
+		checkproc $BBACKUPD_BIN
+		rc_status -v
+		;;
 
     probe)
-	test /etc/box/bbstored.conf -nt /var/run/bbstored.pid && echo reload
-	;;
+		test @sysconfdir_expanded@/box/bbackupd.conf \
+			-nt @localstatedir_expanded@/bbackupd.pid \
+		&& echo reload
+		;;
 
     *)
-	echo "Usage: $0 {start|stop|status|try-restart|restart|force-reload|reload|probe}"
-	exit 1
-	;;
+		echo "Usage: $0 {start|stop|status|try-restart|restart|force-reload|reload|probe}"
+		exit 1
 
 esac
 rc_exit
