Fix errors reported by default Unix notify script on backup-ok events, thanks to Steve Haeck for the bug report.

diff --git a/bin/bbackupd/bbackupd-config.in b/bin/bbackupd/bbackupd-config.in
--- a/bin/bbackupd/bbackupd-config.in
+++ b/bin/bbackupd/bbackupd-config.in
@@ -227,7 +227,7 @@ SUBJECT="BACKUP PROBLEM on host $hostname"
 SENDTO="$current_username"
 
 if [ "\$1" = "" ]; then
-	echo "Usage: \$0 <store-full|read-error|backup-error|backup-start|backup-finish>" >&2
+	echo "Usage: \$0 <store-full|read-error|backup-ok|backup-error|backup-start|backup-finish>" >&2
 	exit 2
 elif [ "\$1" = store-full ]; then
 	$sendmail \$SENDTO <<EOM
@@ -262,7 +262,7 @@ these errors, and take appropriate action.
 Other files are being backed up.
 
 EOM
-elif [ "\$1" = backup-start -o "\$1" = backup-finish ]; then
+elif [ "\$1" = backup-start -o "\$1" = backup-finish -o "\$1" = backup-ok ]; then
 	# do nothing by default
 	true
 else
