Correct typo in the NotifySysadmin.sh generation
git-svn-id: https://www.boxbackup.org/svn/box/trunk@2091 9c52e268-1103-0410-960d-c6a436f6b474

diff --git a/bin/bbackupd/bbackupd-config.in b/bin/bbackupd/bbackupd-config.in
--- a/bin/bbackupd/bbackupd-config.in
+++ b/bin/bbackupd/bbackupd-config.in
@@ -227,7 +227,7 @@ SUBJECT="BACKUP PROBLEM on host $hostname"
 SENDTO="$current_username"
 
 if [ "\$1" = "" ]; then
-	echo "Usage: $0 <store-full|read-error|backup-error|backup-start|backup-finish>" >&2
+	echo "Usage: \$0 <store-full|read-error|backup-error|backup-start|backup-finish>" >&2
 	exit 2
 elif [ "\$1" = store-full ]; then
 	$sendmail \$SENDTO <<EOM
